---
title: "MSK_Impact_result"
author: "Akhilesh"
date: "2022-11-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Pan-Cancer MSK-IMPACT MET Validation Cohort (MSK 2022)
```{r}
mskdat_p <- read.delim("~/Desktop/myproject/data/mixed_impact_subset_2022/data_clinical_patient.txt",header=TRUE,stringsAsFactor = TRUE,comment.char = "#")
  head(mskdat_p)
```
```{r}
mskdat_s <- read.delim ("~/Desktop/myproject/data/mixed_impact_subset_2022/data_clinical_sample.txt",header=TRUE,stringsAsFactor = TRUE,comment.char = "#")
head(mskdat_s)
```
```{r}
mskdat_cna <- read.delim ("~/Desktop/myproject/data/mixed_impact_subset_2022/data_cna.txt",header=TRUE,stringsAsFactor = TRUE,comment.char = "#")
head(mskdat_cna)
```
```{r}
mskdat_m <- read.delim ("~/Desktop/myproject/data/mixed_impact_subset_2022/data_mutations.txt",header=TRUE,stringsAsFactor = TRUE,comment.char = "#")
head(mskdat_m)
```
```{r}
mskdat_cd <- read.delim ("~/Desktop/myproject/data/mixed_impact_subset_2022_clinical_data.txt",header=TRUE,stringsAsFactor = TRUE,comment.char = "#")
head(mskdat_cd)
```


```{r}
#frequency Distribution of CANCER TYPE
library(scales)
table(mskdat_s$CANCER_TYPE)
# generating frequency table
data <- data.frame(table(mskdat_s$CANCER_TYPE))
# relative frequency
num_obsrv <- sum(table(mskdat_s$CANCER_TYPE))
freq<-data[,2]/num_obsrv
data_frame <- data.frame(data, freq)
colnames(data_frame) <- c("CANCER TYPE","#","freq")
# order in descending by frequency
data_frame<-data_frame[order(data_frame$freq,decreasing = TRUE),]
#converting frequency in percentage with accuracy at 2 decimal place 
data_frame$freq <- percent(data_frame$freq, accuracy=.01)
print (data_frame)
```


```{r}
#frequency Distribution of CANCER TYPE DETAILED
library(scales)
table(mskdat_s$CANCER_TYPE_DETAILED)
# generating frequency table
data <- data.frame(table(mskdat_s$CANCER_TYPE_DETAILED))
# relative frequency
num_obsrv <- sum(table(mskdat_s$CANCER_TYPE_DETAILED))
freq<-data[,2]/num_obsrv
data_frame <- data.frame(data, freq)
colnames(data_frame) <- c("CANCER TYPE DETAILED","#","freq")
# order in descending by frequency
data_frame<-data_frame[order(data_frame$freq,decreasing = TRUE),]
#converting frequency in percentage with accuracy at 2 decimal place 
data_frame$freq <- percent(data_frame$freq, accuracy=.01)
print (data_frame)
```

```{r}
#frequency Distribution of Mutated genes
library(scales)
table(mskdat_m$Hugo_Symbol)
# generating frequency table
data <- data.frame(table(mskdat_m$Hugo_Symbol))
# relative frequency
num_obsrv <- 69
freq<-data[,2]/num_obsrv
data_frame <- data.frame(data, freq)
colnames(data_frame) <- c("Mutated genes","#","freq")
# order in descending by frequency
data_frame<-data_frame[order(data_frame$freq,decreasing = TRUE),]
#converting frequency in percentage with accuracy at 2 decimal place 
data_frame$freq <- percent(data_frame$freq, accuracy=.01)
print (data_frame)
```
```{r}
#frequency Distribution of Mutated genes
library(scales)
table(mskdat_m$Hugo_Symbol)
# generating frequency table
data <- data.frame(table(mskdat_m$Hugo_Symbol))
# relative frequency
num_obsrv <- 69
freq<-data[,2]/num_obsrv
data_frame <- data.frame(data, freq)
colnames(data_frame) <- c("Mutated genes","#","freq")
# order in descending by frequency
data_frame<-data_frame[order(data_frame$freq,decreasing = TRUE),]
#converting frequency in percentage with accuracy at 2 decimal place 
data_frame$freq <- percent(data_frame$freq, accuracy=.01)
print (data_frame)
```


```{r}
library(ggplot2)
library(ggpubr)
mskdat_cd$Sample <- seq.int(nrow(mskdat_cd))
ggplot(data = mskdat_cd, aes(x =Fraction.Genome.Altered, y = Mutation.Count,color=Sample,na.rm = TRUE)) + 
  geom_point(size=2, shape=20,na.rm = TRUE) + stat_cor(method = "pearson",label.sep=" Pearson Correlation Coef.,",cor.coef.name = "R",na.rm = TRUE)+
  scale_y_continuous(breaks = seq(0, 37, by = 5)) +scale_x_continuous(breaks = seq(0, 1, by = .1))+
  labs(title = "Mutation Count Vs Fraction Genome Altered ", x = "Fraction Genome Altered", y = "Mutation Count")
```
```{r}
library(ggplot2)
library(ggpubr)
mskdat_cd$Sample <- seq.int(nrow(mskdat_cd))
ggplot(data = mskdat_cd, aes(x =Fraction.Genome.Altered, y = Mutation.Count,color=Sample,na.rm = TRUE)) + 
  geom_point(size=2, shape=20,na.rm = TRUE) + stat_cor(method = "spearman",label.sep=" Spearman Correlation Coef.,", cor.coef.name ="rho",na.rm = TRUE)+
  scale_y_continuous(breaks = seq(0, 37, by = 5)) +scale_x_continuous(breaks = seq(0, 1, by = .1))+
  labs(title = "Mutation Count Vs Fraction Genome Altered ", x = "Fraction Genome Altered", y = "Mutation Count")
```


```{r}

library(ggplot2)
mskdat_cd %>% 
  mutate(Mutation_Count = ifelse(Mutation.Count > 14, 14, ifelse(Mutation.Count <= 2, 2, Mutation.Count))) %>% 
ggplot(aes(Mutation_Count)) + 
  geom_histogram(binwidth =1,col = "black",fill="blue")+scale_y_continuous(breaks = seq(2, 12, by = 2)) +scale_x_continuous(breaks = seq(2, 15, by = 1))+ labs(title = "Mutation Count")
```



```{r}
library(ggplot2)
mskdat_sample_type<-data.frame(table(mskdat_s$SAMPLE_TYPE))
ggplot(mskdat_sample_type,x="",y=mskdat_sample_type[2])+geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0)
